# docker-compose.yml
version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI=mongodb+srv://latihan1:a1C6hj7SrHlOdwtE@cluster1.4mzvn.mongodb.net/
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
